// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soqcgpdhzikxrwdsngnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvcWNncGRoemlreHJ3ZHNuZ252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDI2OTQsImV4cCI6MjA2NTMxODY5NH0.isnRKH5YusiwrxOMt6jCXiS86xjkoZ6LQ5O_mp_V3Go";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);